<?php
//    $canCreate = $this->permissions()->isAllowed($this->identifier, 'create');
$canCreate = true;
?>
<div class="row">
    <div class="col-md-4 col-sm-5 col-xs-12<?php if ($canCreate) : ?> col-md-push-1 col-sm-push-1<?php endif ?>">
    <?php if ($this->showFilter) : ?>
        <form class="form-inline m20-top-down">
            <div class="form-group">
                <label for="exampleInputName2"><?php echo $this->translate('Filter')?>:</label>
                <input class="form-control" type="search" ng-model="filter" placeholder="<?php echo $this->translate('Search') ?>"/>
            </div>
        </form>
    <?php endif ?>
    </div>
    <div class="col-md-7 col-sm-5<?php if ($canCreate) :?> col-sm-push-1 col-md-push-1<?php endif ?> col-xs-12 text-right-not-xs text-center-xs">
        <nav>
            <ul class="pagination">
                <li ng-show="page > 1" ng-click="go_to_<?php echo $this->identifier ?>_page(page-1)">
                    <a href="javascript:void(0)" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li ng-repeat="pg in pages" ng-class="{'active': page == pg }" ng-click="go_to_<?php echo $this->identifier ?>_page(pg)">
                    <a href="javascript:void(0)" >{{pg}}</a>
                </li>
                <li ng-show="page < totalPages" ng-click="go_to_<?php echo $this->identifier ?>_page(page+1)">
                    <a href="javascript:void(0)" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </nav>
    </div>
    <?php if ($canCreate) : ?>
    <div class="col-md-1 col-sm-2 col-md-pull-11 col-sm-pull-10 col-xs-4">
        <a href="" class="btn btn-sm btn-primary m20-top-down" ng-click="focusName($event);_new=true;new_<?php echo $this->identifier ?>()">
          <span class="glyphicon glyphicon-plus"></span>&nbsp;
          <?php echo $this->translate('Add') ?>
        </a>
    </div>
    <?php endif ?>
</div>
<?php if ($this->showInactiveFilter) : ?>
<div class="text-right">
    <?php echo $this->translate('Show Inactive') ?>
    <input ng-toggle-switch="" data-size="mini" data-on-color="danger" type="checkbox" ng-model="$parent.show_inactive_<?php echo $this->identifier ?>" data-off-color="primary" ng-change="get_<?php echo $this->identifier ?>_list()"/>
</div>
<?php endif ?>
