<?php echo $this->doctype(); ?>

<html lang="en" ng-app="forcaDeVendas">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Força de Vendas')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headlink()
            ->appendStylesheet('vendor/bootstrap/css/bootstrap.css')
            ->appendStylesheet('vendor/angular-chart.js/angular-chart.css')
            ->appendStylesheet('vendor/select2/select2.css')
            ->appendStylesheet('css/styles.css');
        ?>
        <?php $this->headScript()->captureStart() ?>
            var BASEURL = '<?php echo $this->basePath(); ?>/';
        <?php $this->headScript()->captureEnd() ?>

        <?php echo $this->headScript()
            ->appendFile('vendor/jquery/jquery.js')
            ->appendFile('vendor/bootstrap/js/bootstrap.js')
            ->appendFile('vendor/angularjs/angular.js')
            ->appendFile('vendor/angular-route/angular-route.js')
            ->appendFile('vendor/angular-bootstrap/ui-bootstrap-tpls.min.js')
            ->appendFile('vendor/angular-resource/angular-resource.js')
            ->appendFile('vendor/angular-local-storage/angular-local-storage.js')
            ->appendFile('vendor/Chart.js/Chart.js')
            ->appendFile('vendor/angular-chart.js/angular-chart.js')
            ->appendFile('vendor/flow.js/flow.js')
            ->appendFile('vendor/ng-flow/ng-flow.js')
            ->appendFile('vendor/select2/select2.js')
            ->appendFile('vendor/jquery.inputmask/jquery.inputmask.js')
            ->appendFile('js/basic.js')
            ->appendFile('js/basket.js')
            ->appendFile('js/crud.js')
            ->appendFile('js/content-editable.js')
            ->appendFile('js/app.js')
        ?>

    </head>
    <body>
        <?php echo $this->content; ?>
        <footer class="footer">
          <div class="container">
            <p class="text-muted">&copy; <?php echo date('Y') ?> Todos os direitos reservados</p>
          </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
