<?php echo $this->doctype(); ?>

<html lang="en" ng-app="forcaDeVendas">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Força de Vendas')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headlink()
            ->appendStylesheet('vendor/bootstrap/bootstrap.css');
        ?>

        <?php echo $this->headScript()
            ->appendFile('vendor/jquery/jquery.js')
            ->appendFile('vendor/bootstrap/bootstrap.js')
            ->appendFile('vendor/angularjs/angular.js')
            ->appendFile('vendor/angular-route/angular-route.js')
            ->appendFile('js/app.js')
        ?>

    </head>
    <body>
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
