<?php

    $identifier = $this->identifier;
    $errorIdentifier = $this->errorIdentifier;
    $disabledCondition = $this->disabledCondition;
?>
<div class="row">
    <div class="col-xs-8">
        <div class="form-group">
            <label><?php echo $this->translate('Street') ?></label>
            <input ng-disabled="<?php echo $disabledCondition ?>" class="form-control" ng-error-message="<?php echo $errorIdentifier ?>.street" ng-model="<?php echo $identifier ?>.street">
        </div>
    </div>
    <div class="col-xs-4">
        <div class="form-group">
            <label><?php echo $this->translate('Number') ?></label>
            <input ng-disabled="<?php echo $disabledCondition ?>" class="form-control" ng-error-message="<?php echo $errorIdentifier ?>.number" ng-model="<?php echo $identifier ?>.number">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-5">
        <div class="form-group">
            <label><?php echo $this->translate('Zipcode') ?></label>
            <input class="form-control" data-integer ng-disabled="<?php echo $disabledCondition ?>" ng-error-message="<?php echo $errorIdentifier ?>.zipcode" ng-model="<?php echo $identifier ?>.zipcode">
        </div>
    </div>
    <div class="col-xs-7">
        <div class="form-group">
            <label><?php echo $this->translate('Complement') ?></label>
            <input class="form-control" ng-disabled="<?php echo $disabledCondition ?>" ng-error-message="<?php echo $errorIdentifier ?>.complement" ng-model="<?php echo $identifier ?>.complement">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-7">
        <div class="form-group">
            <label><?php echo $this->translate('City') ?></label>
            <input class="form-control" ng-disabled="<?php echo $disabledCondition ?>" ng-error-message="<?php echo $errorIdentifier ?>.city" ng-model="<?php echo $identifier ?>.city">
        </div>
    </div>
    <div class="col-xs-5">
        <div class="form-group">
            <label><?php echo $this->translate('Neighborhood') ?></label>
            <input class="form-control" ng-disabled="<?php echo $disabledCondition ?>" ng-error-message="<?php echo $errorIdentifier ?>.neighborhood" ng-model="<?php echo $identifier ?>.neighborhood">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-7">
        <div class="form-group">
            <label><?php echo $this->translate('Phone number') ?></label>
            <input class="form-control" ng-disabled="<?php echo $disabledCondition ?>" ng-error-message="<?php echo $errorIdentifier ?>.phone_number" ng-model="<?php echo $identifier ?>.phone_number">
        </div>
    </div>
    <div class="col-xs-5">
        <div class="form-group">
            <label><?php echo $this->translate('State') ?></label>
            <input class="form-control" ng-disabled="<?php echo $disabledCondition ?>" ng-error-message="<?php echo $errorIdentifier ?>.state" ng-model="<?php echo $identifier ?>.state">
        </div>
    </div>
</div>
