<div class="row">
    <div class="col-xs-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="input-group">
                    <span class="input-group-addon"><?php echo $this->translate('Selected Client') ?></span>
                    <select ng-model="selected_client" class="form-control" ng-options="client as client.name for client in clients track by client.id"></select>
                </div>
            </div>
            <div class="panel-body" ng-show="selected_client">
                <dl>
                    <dt><?php echo $this->translate('Name') ?>:</dt>
                    <dd>{{selected_client.name}}</dd>
                    <dt><?php echo $this->translate('Trading Name') ?>:</dt>
                    <dd>{{selected_client.trading_name}}<dd>
                </dl>
                <dl ng-repeat="address in selected_client.addresses">
                    <dt ng-show="address.type == 'billing'"><?php echo $this->translate('Billing Address') ?></dt>
                    <dt ng-show="address.type == 'delivery'"><?php echo $this->translate('Delivery Address') ?></dt>
                    <dd>{{address.street}}, {{address.number}}, {{address.neighborhood}}, {{address.city}} - {{address.zipcode}} / {{address.state}}</dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="col-xs-6">
        <div class="panel panel-primary">
            <div class="panel-heading"><?php echo $this->translate('Payment') ?></div>
            <div class="panel-body">
                <div class="form-group">
                    <select class="form-control" ng-model="selected.payment" ng-options="payment as payment.name for payment in payments track by payment.id"></select>
                </div>
                <div ng-repeat="form in selected.payment.forms">
                    <input type="radio" ng-model="selected.payment_form" ng-value="form">{{form.description}}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="panel panel-primary">
    <div class="panel-heading"><?php echo $this->translate('Products') ?></div>
    <div class="panel-body">
        <div class="row table-row-title">
            <div class="col-xs-6"><?php echo $this->translate('Name') ?></div>
            <div class="col-xs-1"><?php echo $this->translate('Quantity') ?></div>
            <div class="col-xs-2"><?php echo $this->translate('Unit Price') ?></div>
            <div class="col-xs-2"><?php echo $this->translate('Total Price') ?></div>
        </div>
        <div class="row table-row" ng-repeat="product in products">
            <div class="col-xs-6">
                {{product.name}}
                <div class="row">
                    <div class="col-xs-3">
                        <img src="<?php echo $this->url()?>files.php/{{product.id}}.png" class="img-responsive product-img">
                    </div>
                </div>
            </div>
            <div class="col-xs-1">
                <input type="number" ng-model="product.quantity" ng-change="change(product)" class="form-control"/>
            </div>
            <div class="col-xs-2">
                <span class="price">R$ <big>{{product.price | splitMoney:0}}</big><small>,{{product.price | splitMoney:1}}</small></span>
            </div>
            <div class="col-xs-2">
                <span class="price">R$ <big>{{product.price * product.quantity | splitMoney:0}}</big><small>,{{product.price * product.quantity | splitMoney:1}}</small></span>
            </div>
            <div class="col-xs-1">
                <a ng-click="remove(product)" class="text-danger fake-btn"><span class="glyphicon glyphicon-trash"></span></a>
            </div>
        </div>
        <div class="row table-row">
            <div class="col-xs-offset-7 col-xs-2 text-right">Total dos itens:</div>
            <div class="col-xs-2">R$ <big>{{$parent.basket.total_items | splitMoney:0}}</big><small>,{{$parent.basket.total_items | splitMoney:1}}</small></div>
        </div>
        <div class="row text-success">
            <strong>
                <div class="col-xs-offset-8 col-xs-1 text-right">Total</div>
                <div class="col-xs-2">R$ <big>{{$parent.basket.total | splitMoney:0}}</big><small>,{{$parent.basket.total | splitMoney:1}}</small></div>
            </strong>
        </div>
    </div>
</div>
<button class="btn btn-success" ng-click="finalize()">Finalizar a compra</button>
