<div ng-controller="MainController">
    <div class="header">
        <div class="container">
            <h1 class="pull-left">Força de Vendas</h1>
            <div class="pull-right">
                <img class="pull-left" src="./img/shopping_cart.png" width="60px">
                <div class="pull-right">
                    {{basket.quantity}} itens<br>
                    R$ {{basket.total | splitMoney:0}},{{basket.total | splitMoney:1}}
                </div>

            </div>
            <div class="clearfix"></div>
            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#zf2-navigation-bootstrap3-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="zf2-navigation-bootstrap3-1">
                        <?php
                            echo $this
                                ->navigation('navigation')
                                ->menu()
                                ->setUlClass('nav navbar-nav')
                                ->setPartial('partial/navigation.phtml');
                        ?>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <div ng-view class="container" id="content"></div>
</div>

<script id="main.html" type="text/ng-template">
    <h1>Força de Vendas</h1>
    {{test}}
</script>

<script id="products.html" type="text/ng-template">
    <?php echo $this->partial('partial/products/index.phtml') ?>
</script>
<script id="admproducts.html" type="text/ng-template">
    <?php echo $this->partial('partial/adm/products.phtml') ?>
</script>
<script id="admcategories.html" type="text/ng-template">
    <?php echo $this->partial('partial/adm/categories.phtml') ?>
</script>

<script id="users.html" type="text/ng-template">
    <?php echo $this->partial('partial/users/index.phtml') ?>
</script>

<script id="basket.html" type="text/ng-template">
    <?php echo $this->partial('partial/basket/index.phtml') ?>
</script>
<script id="clients.html" type="text/ng-template">
    <?php echo $this->partial('partial/clients/index.phtml') ?>
</script>
<script id="admpayments.html" type="text/ng-template">
    <?php echo $this->partial('partial/adm/payments.phtml') ?>
</script>
<script id="admorders.html" type="text/ng-template">
    <?php echo $this->partial('partial/adm/orders.phtml') ?>
</script>
